// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
SUMMARIZECOLUMNS(
    'fact_energy_generation'[technology_key],
    "Rows_In_Fact", COUNTROWS('fact_energy_generation'),
    "Sum_GWh", SUM('fact_energy_generation'[generation_gwh])
)